export const SAVE_FILTERED_COURSES = 'SAVE_FILTERED_COURSES';
export const SAVE_ACTIVE_COURSES_FILTER = 'SAVE_ACTIVE_COURSES_FILTER';
export const SAVE_COURSES = 'SAVE_COURSES';
export const COURSES_FETCHING = 'COURSES_FETCHING';
export const COURSES_FETCHED = 'COURSES_FETCHED';
